SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
-- CREATE DATABASE `ap` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
-- ----------------------------
-- Table structure for act_evt_log
-- ----------------------------
DROP TABLE IF EXISTS `ap_invoice`;
CREATE TABLE `ap_invoice`  (
  `INVOICE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LAST_UPDATE_DATE` timestamp NOT NULL,
  `LAST_UPDATED_BY` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `VENDOR_ID` int(11) NULL DEFAULT NULL,
  `INVOICE_NUM` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `SET_OF_BOOKS_ID` int(11) NOT NULL,
  `INVOICE_CURRENCY_CODE` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `PAYMENT_CURRENCY_CODE` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `INVOICE_AMOUNT` DECIMAL(18,2) NULL DEFAULT NULL,
  PRIMARY KEY (`INVOICE_ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin ROW_FORMAT = Dynamic;

INSERT INTO `ap_invoice` (LAST_UPDATE_DATE,LAST_UPDATED_BY,VENDOR_ID,
INVOICE_NUM,SET_OF_BOOKS_ID,INVOICE_CURRENCY_CODE,PAYMENT_CURRENCY_CODE,
INVOICE_AMOUNT) 
VALUES (unix_timestamp(now()),'-1',null,'LD001',101,'CNY','CNY',1000);

SET FOREIGN_KEY_CHECKS = 1;
