SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for act_evt_log
-- ----------------------------
DROP TABLE IF EXISTS `AP_INVOICES_ALL`;
CREATE TABLE `AP_INVOICES_ALL`  (
  `INVOICE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LAST_UPDATE_DATE` timestamp(3) NOT NULL,
  `LAST_UPDATED_BY` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `VENDOR_ID` int(11) NULL DEFAULT NULL,
  `INVOICE_NUM` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `SET_OF_BOOKS_ID` int(11) NOT NULL,
  `INVOICE_CURRENCY_CODE` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `PAYMENT_CURRENCY_CODE` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `INVOICE_AMOUNT` DECIMAL(18,2) NULL DEFAULT NULL,
  PRIMARY KEY (`INVOICE_ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin ROW_FORMAT = Dynamic;


SET FOREIGN_KEY_CHECKS = 1;
